Add API request rate limit
AlexsLemonade/refinebio-py pull request #84
Opened 2023-06-27 20:59 UTC by arkid15r

Resolves #83 

Add API request rate limit using ratelimiter.

Add `api_calls_per_second` to the config. Use 10 as a default if neither `REFINEBIO_API_CALLS_PER_SECOND` env variable nor `api_calls_per_second` config item is available.

2023-07-06 16:08 UTC, davidsmejia requested changes
Looking good! Left a couple comments I'd like you to respond to. I also think that `max_api_calls_per_second` is more descriptive for the option name but I'm not worried about the name.

2023-07-06 16:08 UTC, davidsmejia commented on pyrefinebio/config.py
> +            The refine.bio API calls per second limit
```suggestion
            The refine.bio API calls per second limit. This defaults to the API's rate limit which is enforced per IP address
```

2023-07-07 19:17 UTC, arkid15r reviewed
Thanks for the review. I addressed some of the comments.
Let me know if there is a need for additional changes.

2023-07-07 19:48 UTC, davidsmejia approved these changes
Ok thanks for your response. I checked and it looks like we don't expire tokens. Any further discussion would be best served in a separate issue. So LGTM!

2023-07-07 20:51 UTC, merged